### PR TITLE
Change FLIRT_INCLUDE_DIRS

### PR DESCRIPTION
**Pull request by afakihcpr**
change FLIRT_INCLUDE_DIRS to ${CMAKE_CURRENT_LIST_DIR}/../../../include)

@efernandez @mikepurvis

### CODE REVIEW

**Comment by mikepurvis** [comment]
LGTM, assuming it all still compiles. :)

Do we have any concerns about merge conflicts down the line with this kind of a change? Should we be trying to propose it upstream, or are we a permanent fork at this point?

---

EDIT: Having looked a moment more, I'm not seeing how this could possibly still compile— the headers and srcs are all jumbled up with each other and there's no `flirtlib` prefix on any of the include paths until after installation...

**Comment by efernandez** [comment]
Since this package is catkinized now, I think a bigger change to make it follow the common ROS convention is a good step. I say "bigger" because it seems to me that we should (1) add the flirtlib prefix (as already done), and (2) move all headers to its own `include/flirtlib` folder (with the corresponding subfolders), and (3) simplify the CMakeLists.txt

Thoughts?

**Comment by afakihcpr** [comment]
I have moved all the headers to a separate folder `include/flirtlib` and modified the CMakeLists accordingly. Tested with a fresh build on a clean system and everything builds and installs fine. 

This would be a first step towards making the package follow the common ROS convention as @efernandez mentioned. We should also split it into many packages as we've done with gflip because we basically use only `feature`, `utils` and `geometry`.

I did not move the headers of `gui` because it uses qt moc and we do not depend on `gui` anywhere.

**Comment by efernandez** [comment]
Thanks!

LGTM :+1:

**Comment by mikepurvis** [comment]
LGTM

**Pull request merged**
